name: Deploy Backend

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          source: "."
          target: "~/perfume-backend"
          debug: true
          use_insecure_cipher: true

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd ~/perfume-backend

            echo "ðŸ§¹ Stopping old backend..."
            docker-compose down || true

            echo "ðŸš§ Rebuilding backend image..."
            docker-compose build --no-cache

            echo "ðŸš€ Starting backend container..."
            docker-compose up -d

            echo "âœ… Backend deployed successfully at http://kioskapi.gandom-perfume.ir:1337"
          debug: true
          use_insecure_cipher: true
